# Generated by Django 2.1.2 on 2019-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('authorization', '0004_auto_20191231_1658'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='authorizati_nicknam_b76290_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='apis.App'),
        ),
    ]
